import fs from "fs";
import path from "path";

// Load and parse course data JSON (v5 = v4 data + v3 credits)
const courseDataPath = path.resolve("./controllers/v5.json");
const prereqGraphPath = path.resolve("./controllers/prereq_graph.json");

let allCourses = [];
try {
  allCourses = JSON.parse(fs.readFileSync(courseDataPath, "utf-8"));
} catch (err) {
  console.error("❌ Failed to load course data:", err);
}

// Prereq graph is generated by scripts/build-prereq-graph.mjs; optional at runtime.
let prereqGraph = {};
try {
  prereqGraph = JSON.parse(fs.readFileSync(prereqGraphPath, "utf-8"));
} catch (err) {
  console.error("⚠️ Prereq graph not found — run scripts/build-prereq-graph.mjs:", err.message);
}

const RESULT_CAP = 50;

function normalizeCourseID(query) {
  return query.replace(/[^a-zA-Z0-9]/g, "").toLowerCase();
}

// "CSE 100" -> dept "CSE", number 100 -> level bucket
function deptOf(courseId) {
  const m = courseId.match(/^([A-Z]+)/);
  return m ? m[1] : "";
}

function levelOf(courseId) {
  const m = courseId.match(/(\d+)/);
  if (!m) return "upper";
  const n = parseInt(m[1], 10);
  if (n < 100) return "lower";
  if (n < 200) return "upper";
  return "grad";
}

// Precompute cheap per-course search fields once at startup
const indexed = allCourses.map((course) => ({
  course,
  id: course.course_id,
  normId: (course.normalized_course_id || normalizeCourseID(course.course_id)).toLowerCase(),
  nameLower: (course.course_name || "").toLowerCase(),
  descLower: (course.description || "").toLowerCase(),
  dept: deptOf(course.course_id),
  level: levelOf(course.course_id),
}));

/**
 * filters: {
 *   levels:   array of "lower" | "upper" | "grad"  (empty/missing = all)
 *   depts:    array of department codes, e.g. ["CSE"]  (empty = all)
 *   quarters: array of "FA" | "WI" | "SP" — course must be offered in at
 *             least one selected quarter (empty = all)
 * }
 */
function matchesFilters(entry, filters = {}) {
  const { levels, depts, quarters } = filters;
  if (levels?.length && !levels.includes(entry.level)) return false;
  if (depts?.length && !depts.includes(entry.dept)) return false;
  if (quarters?.length) {
    const offered = entry.course.offerings || [];
    if (!quarters.some((q) => offered.includes(q))) return false;
  }
  return true;
}

/**
 * Ranked search. Tiers: exact id > id prefix > name starts-with > name
 * contains > description contains. Within a tier, catalog (course id) order.
 * Empty query with filters = browse mode over the whole catalog.
 * Returns { results, total } — results capped at RESULT_CAP.
 */
export function searchCourses(query, filters = {}) {
  const trimmed = (query || "").trim();
  const normalized = normalizeCourseID(trimmed);
  const queryLower = trimmed.toLowerCase();

  const pool = indexed.filter((e) => matchesFilters(e, filters));

  if (!queryLower) {
    // Browse mode: no text query, just filters
    const sorted = [...pool].sort((a, b) => a.id.localeCompare(b.id));
    return {
      results: sorted.slice(0, RESULT_CAP).map((e) => e.course),
      total: sorted.length,
    };
  }

  const tiers = [[], [], [], [], []];
  for (const e of pool) {
    if (normalized && e.normId === normalized) tiers[0].push(e);
    else if (normalized && e.normId.startsWith(normalized)) tiers[1].push(e);
    else if (e.nameLower.startsWith(queryLower)) tiers[2].push(e);
    else if (e.nameLower.includes(queryLower)) tiers[3].push(e);
    else if (queryLower.length >= 3 && e.descLower.includes(queryLower)) tiers[4].push(e);
  }

  const ranked = tiers.flatMap((tier) =>
    tier.sort((a, b) => a.id.localeCompare(b.id))
  );

  return {
    results: ranked.slice(0, RESULT_CAP).map((e) => e.course),
    total: ranked.length,
  };
}

/**
 * Departments present in the catalog with course counts, for the browse UI.
 * Counts respect the level filter so "hide grad" shows honest numbers.
 */
export function listDepartments(filters = {}) {
  const counts = new Map();
  for (const e of indexed) {
    if (!matchesFilters(e, { ...filters, depts: [] })) continue;
    counts.set(e.dept, (counts.get(e.dept) || 0) + 1);
  }
  return [...counts.entries()]
    .map(([code, count]) => ({ code, count }))
    .sort((a, b) => a.code.localeCompare(b.code));
}

// ---------------------------------------------------------------------------
// Alias index: lets audit tokens like "ANSC 185" resolve to cross-listed
// catalog entries like "AAS/ANSC 185" (same expansion the graph builder uses)
// ---------------------------------------------------------------------------
function aliasesFor(courseId) {
  const aliases = [courseId];
  // "AAS/ANSC 185" or "BENG/BIMM/CSE/CHEM 182": many subjects, one number
  let m = courseId.match(/^([A-Z]+(?:\/[A-Z]+)+)\s+(\S+)$/);
  if (m) {
    for (const subj of m[1].split("/")) aliases.push(`${subj} ${m[2]}`);
    return aliases;
  }
  // "CHIN 160/260": one subject, many numbers
  m = courseId.match(/^([A-Z]+)\s+(\d+\w*(?:\/\d+\w*)+)$/);
  if (m) {
    for (const num of m[2].split("/")) aliases.push(`${m[1]} ${num}`);
    return aliases;
  }
  // "EDS 31/CHEM 96": full code / full code
  const parts = courseId.split("/");
  if (parts.length > 1 && parts.every((p) => /^[A-Z]+\s+\S+$/.test(p.trim()))) {
    for (const p of parts) aliases.push(p.trim());
  }
  return aliases;
}

const aliasIndex = new Map(); // normalized alias -> indexed entry
for (const e of indexed) {
  for (const alias of aliasesFor(e.id)) {
    const key = normalizeCourseID(alias);
    if (key && !aliasIndex.has(key)) aliasIndex.set(key, e);
  }
}

function courseNumberOf(courseId) {
  const m = courseId.match(/(\d+)/);
  return m ? parseInt(m[1], 10) : null;
}

/**
 * Does the plan/transcript satisfy a course's parsed prerequisites?
 * Advisory only: null means "we can't tell" (unparsed or missing entry).
 */
function checkPrereqsMet(courseId, takenNormSet) {
  const entry = prereqGraph[courseId];
  if (!entry) return { met: null, confidence: "unknown" };
  if (entry.requires.length === 0) {
    // Parsed-and-empty means genuinely no course prereqs; unparsed means
    // there WAS text we couldn't model (e.g. "consent of instructor")
    return {
      met: entry.confidence === "parsed" ? true : null,
      confidence: entry.confidence,
    };
  }
  const met = entry.requires.every((group) =>
    group.some((id) => takenNormSet.has(normalizeCourseID(id)))
  );
  return { met, confidence: entry.confidence };
}

/**
 * Resolve degree-audit course tokens ("DSC 100", "CSE 100TO199") to catalog
 * courses, drop ones already taken/planned, and annotate whether their
 * prerequisites are satisfied by the taken/planned set.
 */
export function recommendCourses(tokens = [], taken = []) {
  const takenNormSet = new Set(taken.map(normalizeCourseID).filter(Boolean));
  const results = [];
  const seen = new Set();

  const push = (token, entry) => {
    if (seen.has(entry.id) || takenNormSet.has(entry.normId)) return;
    seen.add(entry.id);
    const { met, confidence } = checkPrereqsMet(entry.id, takenNormSet);
    results.push({
      token,
      course: entry.course,
      prereqs_met: met,
      prereq_confidence: confidence,
    });
  };

  for (const rawToken of tokens) {
    const token = String(rawToken || "").trim();
    if (!token) continue;

    // Range tokens: "CSE 100TO199" / "MATH 100 TO 199"
    const range = token.match(/^([A-Z&]+)\s*(\d+)[A-Z]*\s*TO\s*(\d+)[A-Z]*$/i);
    if (range) {
      const dept = range[1].toUpperCase();
      const lo = parseInt(range[2], 10);
      const hi = parseInt(range[3], 10);
      for (const e of indexed) {
        if (e.dept !== dept) continue;
        const n = courseNumberOf(e.id);
        if (n !== null && n >= lo && n <= hi) push(token, e);
      }
      continue;
    }

    const entry = aliasIndex.get(normalizeCourseID(token));
    if (entry) push(token, entry);
  }

  return results;
}

/**
 * Prereq-graph info for one course: parsed requirement groups plus the
 * reverse edges ("unlocks"), enriched into lightweight course stubs.
 */
export function courseGraph(courseId) {
  const entry = prereqGraph[courseId];
  if (!entry) return null;

  const stub = (id) => {
    const found = indexed.find((e) => e.id === id);
    return found
      ? {
          course_id: found.id,
          course_name: found.course.course_name,
          credits: found.course.credits,
        }
      : { course_id: id, course_name: "", credits: null };
  };

  return {
    course_id: courseId,
    confidence: entry.confidence,
    requires: entry.requires,
    notes: entry.notes,
    unlocks: entry.unlocks.map(stub),
  };
}

/**
 * Batch offerings lookup for planner-grid warnings. Resolves each code
 * through the alias index (so "ANSC 185" hits the "AAS/ANSC 185" entry).
 * known:false = code isn't in the catalog at all; offerings [] with
 * known:true = in the catalog but no offering evidence.
 */
export function offeringsFor(codes = []) {
  const out = {};
  for (const raw of codes) {
    if (typeof raw !== "string" || !raw.trim()) continue;
    const entry = aliasIndex.get(normalizeCourseID(raw));
    out[raw] = entry
      ? { known: true, offerings: entry.course.offerings || [] }
      : { known: false, offerings: [] };
  }
  return out;
}
