import fs from "fs";
import path from "path";

import { aliasesFor, sequenceMembers } from "../scripts/lib/course-ids.mjs";

// Load and parse course data JSON (v5 = v4 data + v3 credits)
const courseDataPath = path.resolve("./controllers/v5.json");
const prereqGraphPath = path.resolve("./controllers/prereq_graph.json");

let allCourses = [];
try {
  allCourses = JSON.parse(fs.readFileSync(courseDataPath, "utf-8"));
} catch (err) {
  console.error("❌ Failed to load course data:", err);
}

// Prereq graph is generated by scripts/build-prereq-graph.mjs; optional at runtime.
let prereqGraph = {};
try {
  prereqGraph = JSON.parse(fs.readFileSync(prereqGraphPath, "utf-8"));
} catch (err) {
  console.error("⚠️ Prereq graph not found — run scripts/build-prereq-graph.mjs:", err.message);
}

const RESULT_CAP = 50;

function normalizeCourseID(query) {
  return query.replace(/[^a-zA-Z0-9]/g, "").toLowerCase();
}

// "CSE 100" -> dept "CSE", number 100 -> level bucket
function deptOf(courseId) {
  const m = courseId.match(/^([A-Z]+)/);
  return m ? m[1] : "";
}

function levelOf(courseId) {
  const m = courseId.match(/(\d+)/);
  if (!m) return "upper";
  const n = parseInt(m[1], 10);
  if (n < 100) return "lower";
  if (n < 200) return "upper";
  return "grad";
}

// Precompute cheap per-course search fields once at startup
const indexed = allCourses.map((course) => ({
  course,
  id: course.course_id,
  normId: (course.normalized_course_id || normalizeCourseID(course.course_id)).toLowerCase(),
  nameLower: (course.course_name || "").toLowerCase(),
  descLower: (course.description || "").toLowerCase(),
  dept: deptOf(course.course_id),
  level: levelOf(course.course_id),
}));

// A course code shaped like a real one, used to keep a degree audit's credit
// placeholders ("AP **3", "IB MU5") from being mistaken for courses.
// Mirrors _COURSE_CODE_RE in app/planner_agent.py.
const COURSE_CODE_RE = /^[A-Z]{2,6}\s*\d/;
// ...and never contains "*", which is how audits write AP/IB credit
// placeholders ("AP 2D*", "AP 3D*").
const PLACEHOLDER_RE = /\*/;

const tidyCode = (code) =>
  String(code || "").trim().toUpperCase().replace(/\s+/g, " ");

/**
 * An index entry for a course the student's degree audit names but the
 * catalog has never published.
 *
 * These are real: DSC 152 was taught in SP26 and is one of the two
 * alternatives in the Data Science major's Core requirement, while never
 * appearing in catalog.ucsd.edu. Dropping them meant a student could not find
 * — or even see listed — a course their own audit offers them.
 *
 * Everything the catalog would have supplied is genuinely unknown, so nothing
 * is invented: credits stay null rather than 0 so the UI can render "? u"
 * instead of a confident zero, and the empty name/description keep it out of
 * every text-match tier, so it surfaces only when searched for by code.
 * Department and level come from the code itself, which is enough for the
 * level and department filters to treat it like any other course.
 */
function unverifiedEntry(code) {
  const id = tidyCode(code);
  return {
    course: {
      course_id: id,
      course_name: "",
      credits: null,
      prerequisites: "",
      description: "",
      offerings: [],
      professors: [],
      unverified: true,
    },
    id,
    normId: normalizeCourseID(id),
    nameLower: "",
    descLower: "",
    dept: deptOf(id),
    level: levelOf(id),
  };
}

// How many stubs one request may add to the pool. The budget is spent on
// STUBS, not on codes examined: capping the input instead meant the ~500
// perfectly ordinary codes an audit names (all of which resolve and are
// skipped) used up the allowance before the handful of genuinely uncataloged
// ones — the DSC 152 case this whole path exists for — were ever reached.
const VOUCHED_STUB_CAP = 500;

/**
 * Index entries for audit-vouched codes the catalog cannot resolve. Codes it
 * CAN resolve are skipped — they are already in the main index, and a stub
 * would shadow the real entry with an empty one.
 */
function vouchedEntries(codes = []) {
  const out = [];
  const seen = new Set();
  for (const raw of codes) {
    if (out.length >= VOUCHED_STUB_CAP) break;
    const id = tidyCode(raw);
    if (!COURSE_CODE_RE.test(id) || PLACEHOLDER_RE.test(id)) continue;
    const key = normalizeCourseID(id);
    if (!key || seen.has(key) || resolveEntry(id)) continue;
    seen.add(key);
    out.push(unverifiedEntry(id));
  }
  return out;
}

const PLAIN_NUMBER_RE = /^\d+(\.\d+)?$/;

/**
 * A single-quarter view of a dash-joined sequence entry, or null when the
 * query isn't naming one quarter of one.
 *
 * The catalog publishes sequences as one entry ("HILD 2A-B-C") while audits,
 * the Schedule of Classes and students all name the quarters. Returning the
 * sequence for a "HILD 2A" search labels the card with all three quarters, so
 * narrow it: same name and description, but this quarter's id and its own
 * credits. Counterpart of _as_sequence_member in app/catalog.py.
 */
function sequenceMemberView(course, requested) {
  const members = sequenceMembers(course?.course_id || "");
  if (!members.length) return null;
  const want = normalizeCourseID(tidyCode(requested));
  const i = members.findIndex((m) => normalizeCourseID(m) === want);
  if (i === -1) return null;
  // "4-4-4" is per quarter and in order; a single "4" applies to every
  // quarter; anything else (variable-unit seminars) is left alone.
  const parts = String(course.credits ?? "").split("-").map((p) => p.trim());
  const credits =
    parts.length === members.length && parts.every((p) => PLAIN_NUMBER_RE.test(p))
      ? parts[i]
      : course.credits;
  return {
    ...course,
    course_id: members[i],
    normalized_course_id: normalizeCourseID(members[i]),
    credits,
  };
}

/**
 * filters: {
 *   levels:   array of "lower" | "upper" | "grad"  (empty/missing = all)
 *   depts:    array of department codes, e.g. ["CSE"]  (empty = all)
 *   quarters: array of "FA" | "WI" | "SP" — course must be offered in at
 *             least one selected quarter (empty = all)
 * }
 */
function matchesFilters(entry, filters = {}) {
  const { levels, depts, quarters } = filters;
  if (levels?.length && !levels.includes(entry.level)) return false;
  if (depts?.length && !depts.includes(entry.dept)) return false;
  if (quarters?.length) {
    const offered = entry.course.offerings || [];
    if (!quarters.some((q) => offered.includes(q))) return false;
  }
  return true;
}

/**
 * Catalog order: department, then course NUMBER as a number, then the id.
 *
 * Sorting ids as text puts "CSE 100" before "CSE 8A", so browsing CSE showed
 * fifty courses ending at "CSE 15L" and hid the entire introductory sequence
 * (8A, 8B, 20, 21, 30) that most students are actually looking for. Courses
 * with no number at all sort last rather than first.
 */
function byCatalogOrder(a, b) {
  const numOf = (id) => {
    const n = courseNumberOf(id);
    return n === null ? Number.MAX_SAFE_INTEGER : n;
  };
  return (
    a.dept.localeCompare(b.dept) ||
    numOf(a.id) - numOf(b.id) ||
    a.id.localeCompare(b.id)
  );
}

/**
 * Ranked search. Tiers: exact id > id prefix > name starts-with > name
 * contains > description contains. Within a tier, catalog (course id) order.
 * Empty query with filters = browse mode over the whole catalog.
 * Returns { results, total } — results capped at RESULT_CAP.
 */
export function searchCourses(query, filters = {}, vouchedCodes = []) {
  const trimmed = (query || "").trim();
  const normalized = normalizeCourseID(trimmed);
  const queryLower = trimmed.toLowerCase();

  // Audit-vouched courses join the same pool rather than being appended after
  // ranking, so they rank, sort, filter and cap exactly like catalog courses.
  // With no name or description they can only ever land in the id tiers.
  const pool = [...indexed, ...vouchedEntries(vouchedCodes)].filter((e) =>
    matchesFilters(e, filters)
  );

  if (!queryLower) {
    // Browse mode: no text query, just filters
    const sorted = [...pool].sort(byCatalogOrder);
    return {
      results: sorted.slice(0, RESULT_CAP).map((e) => e.course),
      total: sorted.length,
    };
  }

  // Match the id tiers against every form the query could name, not just the
  // literal text: a student searching the way their audit spells a course
  // ("MUS 20R", "HILD 2A") must find the way the catalog spells it ("MUS 20",
  // "HILD 2A-B-C"). aliasesFor returns the query unchanged when it isn't a
  // course code, so a text search is unaffected.
  const queryForms = normalized
    ? [...new Set(aliasesFor(tidyCode(trimmed)).map(normalizeCourseID))].filter(Boolean)
    : [];

  // The alias index is the authority on which catalog entry a written code
  // names, and it knows forms the tier comparisons below cannot derive —
  // "HILD 2C" is the third quarter of "HILD 2A-B-C" but is not a prefix of it,
  // so without this it matched nothing at all.
  const exactEntry = normalized ? resolveEntry(trimmed) : null;

  const tiers = [[], [], [], [], []];
  for (const e of pool) {
    if (e === exactEntry || queryForms.includes(e.normId)) tiers[0].push(e);
    else if (queryForms.some((q) => e.normId.startsWith(q))) tiers[1].push(e);
    else if (e.nameLower.startsWith(queryLower)) tiers[2].push(e);
    else if (e.nameLower.includes(queryLower)) tiers[3].push(e);
    else if (queryLower.length >= 3 && e.descLower.includes(queryLower)) tiers[4].push(e);
  }

  const ranked = tiers.flatMap((tier) => tier.sort(byCatalogOrder));

  // One course_id, one row. A sequence entry narrowed to the quarter asked for
  // ("HILD 7A-B-C" viewed as "HILD 7B") can collide with the standalone row of
  // the same name, which put two "HILD 7B" cards in the results — and, because
  // CourseSearch keys its list on course_id, two React children with the same
  // key. Ranking order decides which one survives.
  const results = [];
  const seenIds = new Set();
  for (const e of ranked) {
    const course = sequenceMemberView(e.course, trimmed) || e.course;
    if (seenIds.has(course.course_id)) continue;
    seenIds.add(course.course_id);
    if (results.length < RESULT_CAP) results.push(course);
  }

  return { results, total: seenIds.size };
}

/**
 * Departments present in the catalog with course counts, for the browse UI.
 * Counts respect the level filter so "hide grad" shows honest numbers.
 */
export function listDepartments(filters = {}) {
  const counts = new Map();
  for (const e of indexed) {
    if (!matchesFilters(e, { ...filters, depts: [] })) continue;
    counts.set(e.dept, (counts.get(e.dept) || 0) + 1);
  }
  return [...counts.entries()]
    .map(([code, count]) => ({ code, count }))
    .sort((a, b) => a.code.localeCompare(b.code));
}

// ---------------------------------------------------------------------------
// Alias index: lets audit tokens like "ANSC 185" resolve to cross-listed
// catalog entries like "AAS/ANSC 185". aliasesFor comes from the shared
// scripts/lib helper rather than being reimplemented here: this file used to
// carry an older copy that disagreed on 277 catalog ids because it lacked the
// "MUS 20R" -> "MUS 20" section-variant rule, so tokens the rest of the stack
// resolved fine matched nothing here.
// ---------------------------------------------------------------------------
//
// TWO passes, exactly like load_catalog() in app/catalog.py: every canonical
// id claims its own key first, and only then do cross-listing aliases fill the
// slots nobody claimed. One pass in catalog order let an alphabetically
// earlier cross-listed row take a standalone course's own key — 50 of them,
// with real consequences: "SIOG 255" (6 units) answered with the 4-unit
// "SIO 104/SIOG 255", and "HILD 7B" answered with the narrowed "HILD 7A-B-C"
// view, whose empty offerings made the planner call a WI/SP course unoffered
// in every term. The two implementations must keep agreeing; a token that
// resolves one way here and another way in the Python planner is a bug in
// whichever one moved.
const aliasIndex = new Map(); // normalized alias -> indexed entry
for (const e of indexed) {
  if (e.normId && !aliasIndex.has(e.normId)) aliasIndex.set(e.normId, e);
}
for (const e of indexed) {
  for (const alias of aliasesFor(e.id)) {
    const key = normalizeCourseID(alias);
    if (key && !aliasIndex.has(key)) aliasIndex.set(key, e);
  }
}

// Audit lines, planner entries and prereq-graph members name a course the way
// the registrar writes it ("DSC 80"); the catalog id is the cross-listed form
// ("DSC 80/80R"). Compare on the canonical id so the two count as one course —
// otherwise a completed prereq matches nothing and the student is told they
// can't take a course they're ready for. Codes with no catalog entry keep
// their own normalized text.
/**
 * The catalog entry a written code refers to, or null.
 *
 * aliasIndex is built by expanding each CATALOG id, which resolves a
 * cross-listing ("DSC 80" -> "DSC 80/80R") but not the other direction: a code
 * only the QUERY spells a special way. Expanding the query too is what makes
 * an audit's section variant ("MUS 20R", "MUS 8GS") find the catalog's base
 * course, and one quarter of a sequence ("HILD 2A") find "HILD 2A-B-C".
 * This is the JS counterpart of get_course in app/catalog.py — without it the
 * server calls those courses uncataloged while the Python planner resolves
 * them fine, and the two disagree about what exists.
 */
function resolveEntry(code) {
  const tidy = tidyCode(code);
  if (!tidy) return null;
  for (const alias of aliasesFor(tidy)) {
    const hit = aliasIndex.get(normalizeCourseID(alias));
    if (hit) return hit;
  }
  return null;
}

const aliasKeyCache = new Map();

/**
 * Every normalized form a written code answers to — its own aliases plus those
 * of the catalog entry it resolves to. Two codes name the same course when
 * these sets intersect.
 *
 * A single canonical key is not enough, because UCSD publishes a cross-listing
 * BOTH as a combined row and as a row per department: "ANTH 268" and
 * "ANTH 268/COGR 225A/HIGR 238/PHIL 209A/SOCG 255A" are the same seminar, and
 * the prereq graph names the combined one while a transcript names the
 * standalone one. Collapsing each side to one key made a completed course fail
 * to satisfy the prerequisite it IS, and told the student they weren't ready.
 */
function aliasKeys(code) {
  const tidy = tidyCode(code);
  if (aliasKeyCache.has(tidy)) return aliasKeyCache.get(tidy);
  const keys = new Set();
  const add = (id) => {
    for (const alias of aliasesFor(id)) {
      const key = normalizeCourseID(alias);
      if (key) keys.add(key);
    }
  };
  if (tidy) add(tidy);
  const entry = resolveEntry(tidy);
  if (entry) add(entry.id);
  aliasKeyCache.set(tidy, keys);
  return keys;
}

// Do two written codes (or a code and a set of them) name the same course?
const namesSameCourse = (code, keySet) => {
  for (const key of aliasKeys(code)) if (keySet.has(key)) return true;
  return false;
};

const allAliasKeys = (codes) => {
  const out = new Set();
  for (const code of codes) for (const key of aliasKeys(code)) out.add(key);
  return out;
};

function courseNumberOf(courseId) {
  const m = courseId.match(/(\d+)/);
  return m ? parseInt(m[1], 10) : null;
}

/**
 * Does the plan/transcript satisfy a course's parsed prerequisites?
 * Advisory only: null means "we can't tell" (unparsed or missing entry).
 */
function checkPrereqsMet(courseId, takenNormSet) {
  const entry = prereqGraph[courseId];
  if (!entry) return { met: null, confidence: "unknown" };
  if (entry.requires.length === 0) {
    // Parsed-and-empty means genuinely no course prereqs; unparsed means
    // there WAS text we couldn't model (e.g. "consent of instructor")
    return {
      met: entry.confidence === "parsed" ? true : null,
      confidence: entry.confidence,
    };
  }
  const met = entry.requires.every((group) =>
    group.some((id) => namesSameCourse(id, takenNormSet))
  );
  return { met, confidence: entry.confidence };
}

/**
 * Resolve degree-audit course tokens ("DSC 100", "CSE 100TO199") to catalog
 * courses, drop ones already completed (or otherwise excluded), and annotate
 * whether their prerequisites are satisfied by the taken/planned set.
 *
 * `exclude` defaults to `taken` for backward compatibility. Callers that want
 * planned courses to remain visible should pass completed-only as `exclude`
 * and completed+planned as `taken` (for prereq ranking).
 */
export function recommendCourses(tokens = [], taken = [], exclude = null) {
  const takenNormSet = allAliasKeys(taken);
  const excludeNormSet = allAliasKeys(exclude == null ? taken : exclude);
  const results = [];
  // De-duplication is PER TOKEN, not global. One course legitimately satisfies
  // several requirements, and the client sends every requirement's codes in
  // one request and regroups the rows by token: a global set meant the first
  // token to claim a course silently emptied every later requirement that
  // offered the same one, and RightSidebar drops a requirement with no courses
  // from "Recommended for you" entirely. It also made the answer depend on the
  // order the tokens arrived in.
  const seenByToken = new Map();

  const push = (token, entry) => {
    const seen = seenByToken.get(token) ?? new Set();
    seenByToken.set(token, seen);
    if (seen.has(entry.id) || namesSameCourse(entry.id, excludeNormSet)) return;
    seen.add(entry.id);
    const { met, confidence } = checkPrereqsMet(entry.id, takenNormSet);
    results.push({
      token,
      course: entry.course,
      prereqs_met: met,
      prereq_confidence: confidence,
    });
  };

  for (const rawToken of tokens) {
    const token = String(rawToken || "").trim();
    if (!token) continue;

    // Range tokens: "CSE 100TO199" / "MATH 100 TO 199"
    const range = token.match(/^([A-Z&]+)\s*(\d+)[A-Z]*\s*TO\s*(\d+)[A-Z]*$/i);
    if (range) {
      const dept = range[1].toUpperCase();
      const lo = parseInt(range[2], 10);
      const hi = parseInt(range[3], 10);
      for (const e of indexed) {
        if (e.dept !== dept) continue;
        const n = courseNumberOf(e.id);
        if (n !== null && n >= lo && n <= hi) push(token, e);
      }
      continue;
    }

    const entry = resolveEntry(token);
    if (entry) {
      push(token, entry);
    } else if (
      COURSE_CODE_RE.test(tidyCode(token)) &&
      !PLACEHOLDER_RE.test(token)
    ) {
      // Every token here came from the degree audit's own requirement lists,
      // so a code the catalog cannot resolve is vouched for by definition —
      // the audit is offering it to this student. Dropping it silently hid
      // DSC 152 from the very requirement that lists it as an option.
      push(token, unverifiedEntry(token));
    }
  }

  return results;
}

/**
 * Prereq-graph info for one course: parsed requirement groups plus the
 * reverse edges ("unlocks"), enriched into lightweight course stubs.
 */
export function courseGraph(courseId) {
  const entry = prereqGraph[courseId];
  if (!entry) return null;

  const stub = (id) => {
    const found = indexed.find((e) => e.id === id);
    return found
      ? {
          course_id: found.id,
          course_name: found.course.course_name,
          credits: found.course.credits,
        }
      : { course_id: id, course_name: "", credits: null };
  };

  return {
    course_id: courseId,
    confidence: entry.confidence,
    requires: entry.requires,
    notes: entry.notes,
    unlocks: entry.unlocks.map(stub),
  };
}

/**
 * Batch offerings lookup for planner-grid warnings. Resolves each code
 * through the alias index (so "ANSC 185" hits the "AAS/ANSC 185" entry).
 * known:false = code isn't in the catalog at all; offerings [] with
 * known:true = in the catalog but no offering evidence.
 */
export function offeringsFor(codes = []) {
  const out = {};
  for (const raw of codes) {
    if (typeof raw !== "string" || !raw.trim()) continue;
    // resolveEntry, not a bare aliasIndex lookup: the index is built from
    // CATALOG ids, so a raw lookup resolves "ANSC 185" but not the forms only
    // the QUERY spells specially. "MUS 20R" and "MUS 8GS" came back
    // known:false here while searchCourses found them, and the planner grid
    // flagged a course the student can genuinely take as not in the catalog.
    const entry = resolveEntry(raw);
    out[raw] = entry
      ? { known: true, offerings: entry.course.offerings || [] }
      : { known: false, offerings: [] };
  }
  return out;
}
